# +---------------------------------+
# |       AutoMinecart Config       |
# +---------------------------------+

# WARNING: DO NOT CHANGE THE "players:" SECTION.
# IT WILL BREAK THE PLUGIN FOR CERTAIN USERS

# Select which worlds you want AutoMinecart to be disabled in.
# Add a dash - and then put the world name like shown below
disabled_worlds:
  - "example_world"

# Set to false if you want the minecart to stay when you exit it
remove_minecart_on_exit: true

# WARNING: DO NOT CHANGE ANYTHING BELOW OR THE PLUGIN WILL BREAK.
players: