# +---------------------------------+
# |       AutoMinecart Config       |
# +---------------------------------+
# Make sure to reload/restart your server for changes to apply.

# Select which worlds you want AutoMinecart to be disabled in.
disabled_worlds:
  - "example_world"